language: node_js
node_js:
  - 'stable'
branches:
  only:
    - master
cache:
  directories:
    - node_modules
script:
  - npm run test
  - npm run build
deploy:
  provider: heroku
  skip_cleanup: true
  keep_history: true
  api_key:
    secure: $HEROKU_API_KEY
  app: redux-saga-demos
  local_dir: build
